### ISSUE TITLE
error on 'npm start'.

### ISSUE THREAD

**Issue by shimoA** [cyamax/nicoSlack#1]
npm start
(electron:17243): Gtk-WARNING **: 10:04:05.349: Theme parsing error: gtk-main.css:73:38: Failed to import: Error opening file /usr/share/themes/Radiance/gtk-3.20/apps/gnome-builder.css: そのようなファイルやディレクトリはありません

os:ubuntu 18.0.4 LTS
これが必要っぽい。
https://www.gtk.org/download/linux.php

**Comment by cyamax** [comment]
Ubuntuでの実行テストはしてなかったな。
エラーを見た感じelectronというよりは、Ubuntu DesktopのGNOME側の問題な気がするけど、ちょっと見てみるよ。

**Comment by cyamax** [comment]
## 検証環境
ubuntu 18.0.4の環境を用意して検証。

## 結果
同じエラーは出なかった。
しかし別のエラーが出て実行不可(libgconf-2.so.4が無い)。
また上記エラーを解決しても、現在利用不可。

このアプリケーションはMacOS or WindowsOSのみ実行可能。

### 詳細
* gnome-builder.css
私の環境のubuntu18.0.4では```/usr/share/themes/Radiance/gtk-3.20/apps/```までのディレクトリは存在したが、```gnome-builder.css```は存在しなかった。
※gnome-*.cssのファイルは４つ存在した
今回のエラーの考えられる原因としてnpmとelectornのバージョンの問題の可能性がある。

* libgconf-2.so.4
```sudo apt install libgconf2-4```で不足したライブラリを入れることで起動できたが、
画面が透過できていなかった。
main.jsで行っている透過処理がubuntuでは異なると考えられる。
